### ISSUE TITLE
Shall we add CircleCI for auto build and deploy this extension.

### ISSUE THREAD

**Issue by heyfirst** [imgrbs/oliv-speedup#11]

**Comment by imgrbs** [comment]
and we should write unit testing, define code style.. whatever about devleoper guide. :dancing_men:

**Comment by imgrbs** [comment]
because it's not good if have bug when deployed hahaha

**Comment by heyfirst** [comment]
@imgrbs agree. make sure we have unit testing, code style definition first. After all, we'll do a pipeline
